sudo: required
  - docker

before_install:
  - docker build -t guilhermecl/docker-k8s-training -f Dockerfile.dev .

script:
  - docker run -e CI=true guilhermecl/docker-k8s-training npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-kubernetes-training"
  env: "DockerKubernetesTraining-env"
  bucket_name: "elasticbeanstalk-us-east-2-322423115285"
  bucket_path: "docker-kubernetes-training"
  on:
    branch: master
  access_key_id: $AWS_ACESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"